[package]
name = "miniasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.5.0", default-features = false }

[dev-dependencies]
hex = "0.4.3"
